In [3]:
# autoreload
%load_ext autoreload
%autoreload 2
%matplotlib inline

import os
import sys

import pathmagic
from tools.project import proj_dir

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
from types import SimpleNamespace
from scripts.train_model import run_model_operation

config = "03_test"

config_dir = "/home/kevin/Documents/master-thesis/code/mt-project/scripts/test_cfg/dummy/"

config_path = config_dir + config + ".json"

# config_path = "/home/kevin/Documents/master-thesis/code/mt-project/scripts/test_cfg/final/08_muc_recurae_coc_big.json"

run_model_operation(SimpleNamespace(
    **{"userfs": False, "test": True, "test_cfg": config_path}))

torch.multiprocessing.set_sharing_strategy('file_system')
Output mode: last
include_all_coc False
Val losses [Masked(MSELoss()), Masked(AccuracyLoss())]
Train loss Masked(MSELoss())
test
Dataset type: test
Test mode

Data dirs ['../../../datasets/s7_real_mp4/test/seq0', '../../../datasets/s7_real_mp4/test/seq1', '../../../datasets/s7_real_mp4/test/seq2']
Ext None
Multi ramp
Ramps in dataset 1
Data class <class 'data.video_depth_focus_data.VideoDepthFocusDataMp4'>
Using stats: ../../../datasets/s7_real_mp4/stats_total.json
Data Stats {'focus_min': 0.1, 'focus_max': 0.5, 'frames': {'depth': {'min': 0, 'max': 1.5}}}
Using hardcoded min depth 0.03!!!
depth_normalize: Normalize(0.03, 1.5, clamp_max=False)
coc_normalize: None
signed_coc_normalize: None
Latest epoch = 10
Type: <class 'dict'>
Error loading optimizer state dict -> OK since in test mode
16:54:30 Loaded checkpoint
16:54:30 [Epoch 10] TRAIN train_loss: 2.1965470
16:54:30 [Epoch 10] VAL   train_loss: 1.5283622 mse: 1.5283622 acc: 4

[ 0 24 67 90] [0.1        0.18788439 0.36224484 0.4487434 ]
[ 0 21 65 87] [0.1        0.18499847 0.3594798  0.4487434 ]
[ 0 16 61 82] [0.1        0.18571141 0.36505324 0.4487434 ]
[ 0 24 68 89] [0.1        0.18936221 0.36505324 0.4487434 ]
<class 'numpy.ndarray'> [640, 480]
Identity
<class 'numpy.ndarray'> [640, 480]
Identity
<class 'numpy.ndarray'> [640, 480]
Identity
[ 0 17 62 83] [0.1        0.18571141 0.36505324 0.4487434 ]
<class 'numpy.ndarray'> [640, 480]
Identity
[ 0 16 60 82] [0.1        0.18571141 0.36224484 0.4487434 ]
[ 0 17 61 83] [0.1        0.18571141 0.36224484 0.4487434 ]
[ 0 17 61 83] [0.1        0.18643    0.36224484 0.4487434 ]
<class 'numpy.ndarray'> [640, 480]
Identity
<class 'numpy.ndarray'> [640, 480]
Identity
<class 'numpy.ndarray'> [640, 480]
Identity
[ 0 17 61 84] [0.1        0.18571141 0.36224484 0.4487434 ]
<class 'numpy.ndarray'> [640, 480]
Identity
<class 'numpy.ndarray'> [640, 480]
Identity
[ 0 17 61 82] [0.1        0.18643    0.36505324 0.4487434 ]
[ 0 